### ISSUE TITLE
Doesn't work anymore with google-chrome

### ISSUE THREAD

**Issue by pblayo** [robinst/jar-manifest-formatter#4]
When copy-paste an OSGi manifest content in firefox it works as well as before but in chrome, there's an error (in IE as well):

```
script.js:36 Uncaught TypeError: undefined is not a function
```

where line 36 is

```
header.value.match(/([^,"]+|"[^"]*")+\s*/g).map(String.trim);
```

And indeed when we execute `String.trim` in chrome we got:

```
String.trim is not a function
```

**Comment by robinst** [comment]
Thanks, should be fixed now! Also added tests to catch this in the future.

**Comment by pblayo** [comment]
Thanks for the push of a commit that shows the issue occurs also on node.js with Travis and thanks for the Unit Tests addition.
