### ISSUE TITLE
Unlimited width ?

### ISSUE THREAD

**Issue by paulvi** [robinst/jar-manifest-formatter#5]
There is quite a beast. Can you make form wider or unlimited (screen width)

![osgi1](https://cloud.githubusercontent.com/assets/1614482/15529079/e0d90d16-227c-11e6-868e-cb50b83456b8.PNG)

**Comment by paulvi** [comment]
Closing as silly, size can be adjusted with mouse.

**Comment by robinst** [comment]
No worries :).
